### ISSUE TITLE
RateLimiterDynamo - TypeError: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by drivedemon** [animir/node-rate-limiter-flexible#306]
Hi got this error:
I'm following the [wiki doc](https://github.com/animir/node-rate-limiter-flexible/wiki/DynamoDB). and implemented with serverless framework also installed aws-sdk@2

I try to debug the DynamoDB instance and the query is connected
The table is already created by cloud information and gives access can read and write to the table
```
TypeError: Cannot read properties of undefined (reading 'key')
```

rateLimiter.ts
```
import { RateLimiterDynamo } from 'rate-limiter-flexible'
import DynamoDB from 'aws-sdk/clients/dynamodb'
import {awsConfig} from "~/config"

export async function createDynamoDbRateLimiter(): Promise<RateLimiterDynamo> {
    const dynamoClient = new DynamoDB();

    return new Promise<RateLimiterDynamo>((resolve, reject) => {
        const rateLimiter = new RateLimiterDynamo(
            {
                storeClient: dynamoClient,
                tableCreated: true,
                tableName: awsConfig.dynamodb.apiRequestTable.name,
                points: 2,
                duration: 15,
            },
            (err: Error | null) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(rateLimiter);
                }
            }
        );
    });
}
```

handler.ts
```
await createDynamoDbRateLimiter()
        .then((rateLimiterDynamo) => {
          rateLimiterDynamo.consume('user-id')
              .then((rateLimiterRes) => {
                // success
              })
              .catch((rateLimiterResOrError) => {
                // still got error and throw message as 'key' undefined
              })
        })
        .catch((err) => {
          //
        })
```

**Comment by animir** [comment]
@drivedemon Hey.
Could you check the value in `awsConfig.dynamodb.apiRequestTable.name` ?
Could you let me know if you are sure the table is created?

If table name is a string and table is created could you debug `RateLimiterDynamo` in your node_modules? I'll help with that.
I am not sure why data returned from `updateItem` command doesn't contain `Attributes`. Could you debug (or console.log) `data` variable after this line https://github.com/animir/node-rate-limiter-flexible/blob/165363f1bb4ac654a2dd4a7388f624eabce5d782/lib/RateLimiterDynamo.js#L290 ?

**Comment by drivedemon** [comment]
Hi @animir 
I saw old post and they suggest changing import from `aws-sdk` to `@aws-sdk/client-dynamodb` and its works fine
I can connected now but return this error. Can you help me take a look what is mistake?

```
The provided key element does not match the schema
```

serverless.yml
```
resources:
  Resources:
    ApiRequestTableV2:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: '${self:service}-${self:provider.stage}-api-requests-v2'
        TableClass: 'STANDARD'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expireAt
          Enabled: true
```

rateLimiter.ts
```
import DynamoDB from 'aws-sdk/clients/dynamodb'
=>
import { DynamoDB as DynamoDBv2 } from '@aws-sdk/client-dynamodb'

const dynamoClient = new DynamoDBv2({
                region: awsConfig.region,
                credentials: {
                    accessKeyId: awsConfig.accessKeyId,
                    secretAccessKey: awsConfig.secretAccessKey,
                },
                endpoint: `https://dynamodb.${awsConfig.region}.amazonaws.com`,
            })
            dynamoClient.listTables({}, (err, data) => {
                if (err) logger.error('Error listing tables:', err);
                else logger.info('Tables:', data);
            });

            rateLimiter = new RateLimiterDynamo({
                storeClient: dynamoClient,
                tableCreated: true,
                tableName: awsConfig.dynamodb.apiRequestTable.name,
                points: 4
                duration: 1,
            })
```

handler.ts
```
const apiKey = event.headers?.['key'] ?? 'unknown'
await applyRateLimit(apiKey)
```
